### PR TITLE
[WIP] Setup deploy process for UI

### LINKED ISSUE #151: Deploy FrontEnd Using Netlify

### PR DESCRIPTION
**Pull request by pradel**
In order to be able to deploy to s3 we need to wait this pr to be merged: https://github.com/fernando-mc/serverless-finch/pull/12.

I simplified the npm scripts commands:
- to start a backend just run `yarn start`
- to deploy just run `yarn deploy-prod`

To deploy the ui:
- deploy to netlify
- deploy to s3
client-bucket-name
capture d ecran 2017-11-25 a 18 06 20

Close #151

### CODE REVIEW

**Comment by pradel** [comment]
@sid88in any thought?
I think once the pr for serverless-finch is merged we are good to merge this one :)

**Comment by sid88in** [comment]
@pradel do you have a rough ETA on merging the dependency ? If we don't have that yet, do you think its better to not depend of serverless-flinch and maybe deploy using other mechanisms?

**Comment by sid88in** [comment]
@pradel your dependencies are merged. Can you please add screenshots with explanation about this PR and correct steps to deploy UI to frontend? we can then merge this PR. 

thanks!

**Comment by sid88in** [comment]
+ @nikgraf

**Comment by pradel** [comment]
@sid88in Okay will do that!

**Comment by pradel** [comment]
@sid88in Should be good now

**Pull request merged**
