### PR TITLE
Add prettier and eslint

### LINKED ISSUE #88: Introduce Prettier

### PR DESCRIPTION
**Pull request by pradel**
Hey, thanks for this great example it is really helpfull 😄 

This pr close #88 
- Move eslint config at the root folder, so now the client and backend folder are linted
- Add a prettier config compatible with eslint
- Fix the lint for the client and backend folder
- Add a git hook that prettier the files before commit

### CODE REVIEW

**Comment by sid88in** [comment]
@pradel this is awesome !! I'll do one round of testing and then merge this PR ;)  Looking forward to more contributions :)

**Comment by sid88in** [comment]
@pradel can you please do functional testing of this PR? I tried to test this PR by running it on local and see some errors (attached screenshot in the PR). Please let me know if I am missing anything. 

thanks
Sid

**Comment by sid88in** [comment]
@pradel I am going to merge this PR and fix the bug in another PR.

**Comment by nikgraf** [comment]
really nice changes @pradel

**Pull request merged**
